# Generated by Django 4.1 on 2022-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerBusiness",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerHumanity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
