# Generated by Django 4.1 on 2022-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0002_alter_partner_id_alter_partnerbusiness_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("college", models.CharField(default="", max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="partner",
            name="college",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="partnerbusiness",
            name="college",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="partnerhumanity",
            name="college",
            field=models.CharField(default="", max_length=15),
        ),
    ]
