# Generated by Django 4.1 on 2022-08-17 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intro", "0003_partnerall_partner_college_partnerbusiness_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerall",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerall",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
