# Generated by Django 4.1 on 2022-08-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0005_partner_like_partner_like_count_partnerbusiness_like_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="PartnerAll",),
    ]
