# Generated by Django 4.1 on 2022-08-18 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intro", "0006_delete_partnerall"),
    ]

    operations = [
        migrations.RemoveField(model_name="partner", name="college",),
        migrations.RemoveField(model_name="partnerbusiness", name="college",),
        migrations.RemoveField(model_name="partnerhumanity", name="college",),
        migrations.CreateModel(
            name="PartnerVet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_vet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerSociety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_society",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerScience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_science",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerMixed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_mixed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_medicine",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_life",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_farm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_engine",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerElec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_elec",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
