# Generated by Django 4.1 on 2022-08-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0007_remove_partner_college_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="like_count",
            field=models.PositiveIntegerField(),
        ),
    ]
