# Generated by Django 4.1 on 2022-08-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intro", "0009_alter_partner_like_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="partner", name="like",),
        migrations.RemoveField(model_name="partner", name="like_count",),
        migrations.RemoveField(model_name="partnerbusiness", name="like",),
        migrations.RemoveField(model_name="partnerbusiness", name="like_count",),
        migrations.RemoveField(model_name="partnerdoctor", name="like",),
        migrations.RemoveField(model_name="partnerdoctor", name="like_count",),
        migrations.RemoveField(model_name="partnerelec", name="like",),
        migrations.RemoveField(model_name="partnerelec", name="like_count",),
        migrations.RemoveField(model_name="partnerengine", name="like",),
        migrations.RemoveField(model_name="partnerengine", name="like_count",),
        migrations.RemoveField(model_name="partnerfarm", name="like",),
        migrations.RemoveField(model_name="partnerfarm", name="like_count",),
        migrations.RemoveField(model_name="partnerhumanity", name="like",),
        migrations.RemoveField(model_name="partnerhumanity", name="like_count",),
        migrations.RemoveField(model_name="partnerlife", name="like",),
        migrations.RemoveField(model_name="partnerlife", name="like_count",),
        migrations.RemoveField(model_name="partnermedicine", name="like",),
        migrations.RemoveField(model_name="partnermedicine", name="like_count",),
        migrations.RemoveField(model_name="partnermixed", name="like",),
        migrations.RemoveField(model_name="partnermixed", name="like_count",),
        migrations.RemoveField(model_name="partnerscience", name="like",),
        migrations.RemoveField(model_name="partnerscience", name="like_count",),
        migrations.RemoveField(model_name="partnersociety", name="like",),
        migrations.RemoveField(model_name="partnersociety", name="like_count",),
        migrations.RemoveField(model_name="partnerteacher", name="like",),
        migrations.RemoveField(model_name="partnerteacher", name="like_count",),
        migrations.RemoveField(model_name="partnervet", name="like",),
        migrations.RemoveField(model_name="partnervet", name="like_count",),
    ]
