# Generated by Django 4.1 on 2022-08-19 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intro", "0010_remove_partner_like_remove_partner_like_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerbusiness",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_business", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerbusiness",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerdoctor",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_doctor", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerdoctor",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerelec",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_elec", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerelec",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerengine",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_engine", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerengine",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerfarm",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_farm", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerfarm",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerhumanity",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_humanity", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerhumanity",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerlife",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_life", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerlife",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnermedicine",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_medicine", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnermedicine",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnermixed",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_mixed", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnermixed",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerscience",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_science", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerscience",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnersociety",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_society", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnersociety",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerteacher",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_teacher", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnerteacher",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnervet",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes_vet", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="partnervet",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
