# Generated by Django 4.1 on 2022-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="partner",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
