# Generated by Django 4.1 on 2022-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerapp", "0002_alter_partner_address_alter_partner_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerBusiness",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerHumanity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=300)),
                ("address", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
