# Generated by Django 4.1 on 2022-08-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partnerapp", "0005_post_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
    ]
