# Generated by Django 4.1 on 2022-08-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partnerapp", "0006_remove_post_author"),
    ]

    operations = [
        migrations.DeleteModel(name="Partner",),
        migrations.DeleteModel(name="PartnerBusiness",),
        migrations.DeleteModel(name="PartnerHumanity",),
    ]
