# Generated by Django 4.1 on 2022-08-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerapp", "0007_delete_partner_delete_partnerbusiness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="hit", field=models.PositiveIntegerField(default=0),
        ),
    ]
